---
title: "Bradley-Terry"
output: html_document
date: "2023-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Creating super function

TennisTidyr<-function(startyear,endyear,testset,numgames,filename,keepNAheight,keepNAage){
  # Adding errors for if years will not match the dataset
  if (!(startyear > 1967 & startyear < 2023)){
    return("Error: Start year must be between 1968 and 2022")
  }
  if (!(endyear > 1967 & endyear < 2023)){
    return("Error: End year must be between 1968 and 2022")
  }
  if (!(testset > 1967 & testset < 2024)){
    return("Error: Test set must be between 1968 and 2023")
  }
  if (startyear > endyear){
    return("Error: Start year must be less than end year")
  }
  if (endyear > testset){
    return("Error: End year must be less than test set")
  }
  
  #Creating blank dataset for training set, then appending each year
  train<-tibble()
  num_names<-c()
  for (i in startyear:endyear){
    data<-read_csv(paste(filename,as.character(i),".csv", sep=""),show_col_types = FALSE)
    num_names<-append(num_names,c(as.matrix(data[,'winner_name']),as.matrix(data[,'loser_name'])))
    train<-rbind(train,data)
  }
  #List of all unique names in that time period
  names<-unique(num_names)
  
  #Number of games played per player
  N<-length(names)
  num_games<-rep(0,N)
  for (i in 1:N){
    num_games[i]<-length(which(num_names==names[i]))
  }
  
  #Players who played in the test set (2023)
  test_set<-read_csv(paste(filename,as.character(testset),".csv", sep=""),show_col_types = FALSE)
  test_names<-c(as.matrix(test_set[,'winner_name']),as.matrix(test_set[,'loser_name']))

  #List of 'significant' players
  main_names<-names[num_games > numgames & names %in% test_names]
  
  #Only selecting columns we currently care about
  train<-train[,c('surface','winner_name','winner_hand','winner_ht','winner_age','loser_name','loser_hand','loser_ht','loser_age')]
  test<-test_set[,c('surface','winner_name','winner_hand','winner_ht','winner_age','loser_name','loser_hand','loser_ht','loser_age')]

  #Only selecting players we care about
  train<-train[train$winner_name %in% main_names,]
  train<-train[train$loser_name %in% main_names,]
  
  test<-test[test$winner_name %in% main_names,]
  test<-test[test$loser_name %in% main_names,]
  
  #Removing missing heights and ages if required
  if (keepNAheight==FALSE){
    train<-train[!is.na(train$winner_ht),]
    train<-train[!is.na(train$loser_ht),]
    test<-test[!is.na(test$winner_ht),]
    test<-test[!is.na(test$loser_ht),]
  }
  
  if (keepNAage==FALSE){
    train<-train[!is.na(train$winner_age),]
    train<-train[!is.na(train$loser_age),]
    test<-test[!is.na(test$winner_age),]
    test<-test[!is.na(test$loser_age),]
  }
  
  
  return(list(train,test,main_names))
}


```

```{r warning=FALSE}
#IMPORTING DATA

data<-TennisTidyr(2013,2021,2023,5,"data/wta_matches_",FALSE,FALSE)

test<-data[[1]]
names<-data[[3]]

test$winner_name <- data.frame(name = test$winner_name, hand = test$winner_hand)
test$loser_name <- data.frame(name = test$loser_name, hand = test$loser_hand)

test$winner_name$name<-factor(test$winner_name$name,levels=names)
test$loser_name$name<-factor(test$loser_name$name,levels=names)




BTModel<-BTm(outcome = 1, winner_name,loser_name,data=test,formula=~name+hand,family = binomial(link = "logit"))

BTModel

BTabilities(BTModel)
```

```{r}
unique(c(test$winner_name[which(is.na(test$winner_ht))],test$winner_name[which(is.na(test$winner_ht))]))

noheights<-unique(test$winner_name[which(is.na(test$winner_ht))])

length(names[!(names %in% noheights)])

unique(c(test$winner_name[which(is.na(test$winner_ht))],test$loser_name[which(is.na(test$loser_ht))]))

(test$winner_name[which(is.na(test$winner_ht))],test$loser_name[which(is.na(test$loser_ht))])

test$winner_name[which(is.na(test$winner_ht))]
```

```{r}
data(baseball)

baseballModel1 <- BTm(cbind(home.wins, away.wins), home.team, away.team,
data = baseball, id = "team")

baseballModel1
```

```{r}
baseball$home.team <- data.frame(team = baseball$home.team, at.home = 1)
baseball$away.team <- data.frame(team = baseball$away.team, at.home = 0)

baseball
```

```{r}
baseballModel2 <- update(baseballModel1, formula = ~ team + at.home)

BT

```

```{r}
test
```

```{r}
test$winner_name <- data.frame(name = test$winner_name, hand = test$winner_hand)
test$loser_name <- data.frame(name = test$loser_name, hand = test$loser_hand)

BTModel2 <- update(BTModel, formula = ~ name + hand)
```

```{r}
ranks<-BTabilities(model_3vars)
proper_ranks<-data_frame(Player=sort(players$Player),Rank=ranks[1:126])
proper_ranks[order(proper_ranks$Rank,decreasing=TRUE),]
```


