---
title: "Time_Series"
output: html_document
date: "2024-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(BradleyTerry2)

```

```{r warning=FALSE}
# PICKING 5 MOST IMPORTANT PLAYERS??

#Loading data
Big_Data<-TennisTidyr(2013,2022,2023,5)

Big_Train<-Big_Data$train
players<-Big_Data$main_names

#Number of top players
M<-5

#Training model
weights <- get_recency_weights(Big_Train, 0.9)
Big_Model <- BTm(outcome=1, factor(winner_name, levels=players), factor(loser_name, levels=players), 
                    weights = weights, id='player', data=Big_Train)



#Finding top players
Big_Rankings<-data_frame(Players=players,Ranks=BTabilities(Big_Model)[,1])
Big_Rankings<-Big_Rankings[order(Big_Rankings$Ranks,decreasing=TRUE),]
top_players<-Big_Rankings$Players[1:M]

```

```{r}
top_players
```


```{r}
#Function for finding rankings
Ranks<-function(year){
  #Loading data
  Data<-TennisTidyr(year-3,year,2023,1)
  Train<-Data$train
  players<-Data$main_names


#Training model
weights <- get_recency_weights(Train, 0.1)
Model <- BTm(outcome=1, factor(winner_name, levels=players), factor(loser_name, levels=players), 
                    weights = weights, id='player', data=Train)

#Finding top players
Rankings<-data_frame(Players=players,Ranks=BTabilities(Model)[,1])
Rankings<-Rankings[order(Rankings$Ranks,decreasing=TRUE),]

#Finding the ranks of each top player. If they have none, we output NA
ranks<-rep(0,M)
for (i in 1:M){
  if(top_players[i] %in% Rankings$Players){
  ranks[i]<-which(Rankings$Players == top_players[i])
  }
  else{
    ranks[i]<-NA
  }
}
return(ranks)
}
```

```{r warning=FALSE}
#Matrix for rankings
Rankings_Mat<-matrix(NA,nrow=M,ncol=7)

for (i in 2016:2022){
  Rankings_Mat[,i-2015]<-Ranks(i)
}
```

```{r}
library(scales)
library(ggthemes)
n=7

#Transforming data to fit ggplot2
Rankings_Data<-as.data.frame(t(Rankings_Mat),row.names = seq(2016,2022))
colnames(Rankings_Data)<-top_players
longDat <- Rankings_Data %>% pivot_longer(cols = everything(), names_to = "Players", values_to = "Ranks") %>% dplyr::arrange(Players)
longerDat<-longDat %>% group_by(Players) %>%
            slice(1:n) %>%
            mutate(Year = as.numeric(row_number()+2015))
breaks = seq(min(longerDat$Year),max(longerDat$Year), length.out = n)

#Plotting
timeplot1<-ggplot(longerDat,aes(x = Year, y = Ranks, col = Players)) +
            geom_point() +
            geom_line() +
  theme_solarized() +
  scale_y_reverse() +
   theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1)) +
  scale_x_continuous(labels = label_number(accuracy = 1),breaks=breaks) +
  labs(x='Year',y='Ranking',title='Rankings from 2010-2019')
  
  timeplot1
```

```{r}
#PLOTTING WTA RANK AGAINST OURS

#Function for finding WTA rankings
WTA_Ranks<-function(year){
  data<-read.csv(paste('data/wta_matches_',year,'.csv',sep=''))
  ranks<-rep(NA,M)
  for (i in 1:M){
    possible_ranks<-data$winner_rank[data$winner_name==top_players[i]]
    if(length(possible_ranks>0)){
      ranks[i]<-min(possible_ranks)
    }
  }
  return(ranks)
}
```

```{r}
#Matrix for rankings
WTA_Rankings_Mat<-matrix(NA,nrow=M,ncol=7)

for (i in 2016:2022){
  WTA_Rankings_Mat[,i-2015]<-WTA_Ranks(i)
}

WTA_Rankings_Data<-as.data.frame(t(WTA_Rankings_Mat),row.names = seq(2016,2022))
colnames(WTA_Rankings_Data)<-top_players
longDat <- WTA_Rankings_Data %>% pivot_longer(cols = everything(), names_to = "Players", values_to = "Ranks") %>% dplyr::arrange(Players)
WTA_longerDat<-longDat %>% group_by(Players) %>%
            slice(1:7) %>%
            mutate(Year = as.numeric(row_number()+2015))

WTA_longerDat$Ranks[WTA_longerDat$Players=='Iga Swiatek' & WTA_longerDat$Year==2018]<-NA
```


```{r}
ggplot(longerDat,aes(x = Year, y = Ranks, col = Players)) +
            geom_point() +
            geom_line() +
    geom_line(data=WTA_longerDat,aes(x = Year, y=Ranks, col=Players),linetype=3) +
  theme_solarized() +
  scale_y_reverse() +
   theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1)) +
  scale_x_continuous(labels = label_number(accuracy = 1),breaks=breaks) +
  labs(x='Year',y='Ranking',title='Rankings from 2010-2019') 


```

```{r}
WTA_longerDat[!WTA_longerDat$Players=='Elina Svitolina',]

ggplot(longerDat[!longerDat$Players=='Elina Svitolina',],aes(x = Year, y = Ranks, col = Players)) +
            geom_point() +
            geom_line() +
    geom_line(data=WTA_longerDat[!WTA_longerDat$Players=='Elina Svitolina',],aes(x = Year, y=Ranks, col=Players),linetype=3) +
  theme_solarized() +
   
  scale_y_reverse() +
   theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1)) +
  scale_x_continuous(labels = label_number(accuracy = 1),breaks=breaks) +
  labs(x='Year',y='Ranking',title='Rankings from 2010-2019') 
```

```{r}
top_players[]
```

